spring.application.name=Ms.Adopcion

server.port=8086

spring.datasource.url=jdbc:mysql://mysql-35e6df79-varas5011-9353.c.aivencloud.com:12467/adopcion?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.enabled=false
spring.cloud.discovery.enabled=false